server : *.java ../web_interface/src/ballmerpeak/turtlenet/server/Message.java
	@cp ../web_interface/src/ballmerpeak/turtlenet/server/Message.java Message.java
	@javac *.java
clean : *.class
	@rm *.class
run : Server.class
	@java Server
